#!/bin/bash

# CONFIG
AURGITCLONE=/home/td123/tmp/aurgitclone
AURTEST=/home/td123/tmp/aurtest

# SANITY CHECKS
[ ! -d $AURGITCLONE ] && echo "run: git clone /srv/git/aur.git/ $AURGITCLONE"j&& exit 1
[ ! -d $AURTEST ] &&  echo "run: install -d $AURTEST" && exit 1

# HARDCORE SYNCING
cd $AURTEST
rm -f /tmp/rlog
rsync -avz --include '/*.tar.gz' --exclude '/*' --exclude '/.git/' --temp-dir '/tmp' --inplace --update --delete \
      'rsync://aur.archlinux.org/unsupported/*/' . |& tee /tmp/rlog

# SOFTCORE PROCESSING
cd $AURGITCLONE
while read line; do
  match=$(echo $line | sed -n 's/^deleting \(.*\).tar.gz/\1/p')

  if [[ x$match != x ]]; then
    rm -rf ${match}
    #echo deleted
  else
    match=$(echo $line | sed -n 's/^\(.*\).tar.gz/\1/p')
    if [[ x$match != x ]]; then
      #echo updated
      rm -rf ${match}
      bsdtar xf $AURTEST/$match.tar.gz
    fi
  fi
done < /tmp/rlog
rm -f /tmp/rlog

# GIT ER DONE
git add *
git commit -am "updated on $(date)"
git push

